name: Deploy Flutter Mini-App

on:
  push:
    tags:
      - 'v*'      

env:
  APP_DEPLOY_PATH: /var/www/app.tarot-book.ru

jobs:
  build:
    name: 💪 Build Mini-App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if tag is on master
        run: |
          BRANCH=$(git branch -r --contains $GITHUB_SHA | grep origin/master || true)
          if [[ -z "$BRANCH" ]]; then
            echo "❌ Tag is not on master. Skipping."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Install dependencies
        run: flutter pub get
        

      - name: Build Flutter Web
        run: flutter build web
        

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: miniapp-web
          path: build/web

  deploy:
    name: 🏠 Deploy to Server
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: miniapp-web

      - name: Upload to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: miniapp-web/*
          target: ${{ env.APP_DEPLOY_PATH }}
